### ISSUE TITLE
undefined method `any?' for ...

### ISSUE THREAD

**Issue by davezen316** [Sology/smart_listing#121]
Error occur when I am trying to sorting the list

it returns

> GET http://localhost:3000/customers?customers_smart_listing%5Bpage%5D=&customer…ting%5Bper_page%5D=10&customers_smart_listing%5Bsort%5D%5Bfirstname%5D=asc 500 (Internal Server Error)

on the console

and when I go to the link it gave me error as below:
**undefined method `any?' for #<ActionController::Parameters:0x007fb410c552a8>**

```
#GET /customers.json
  def index
    @customers = smart_listing_create(:customers, Customer.all, partial: "customers/listing")
  end

#GET /customers/1
```
I am currently working with ruby 2.4.0 and rails 5.1.1

**Comment by beneggett** [comment]
the PR by @phoffer fixes it for us
