### PR TITLE
Use #empty? for AC::Params (Rails 5.1 compatibility)

### LINKED ISSUE #121: undefined method `any?' for ...
Error occur when I am trying to sorting the list

it returns

> GET http://localhost:3000/customers?customers_smart_listing%5Bpage%5D=&customer…ting%5Bper_page%5D=10&customers_smart_listing%5Bsort%5D%5Bfirstname%5D=asc 500 (Internal Server Error)

on the console

and when I go to the link it gave me error as below:
**undefined method `any?' for #<ActionController::Parameters:0x007fb410c552a8>**

```
#GET /customers.json
  def index
    @customers = smart_listing_create(:customers, Customer.all, partial: "customers/listing")
  end

#GET /customers/1
```
I am currently working with ruby 2.4.0 and rails 5.1.1

### PR DESCRIPTION
**Pull request by phoffer**
[ActionController::Params does not inherit from HashWithIndifferentAccess anymore](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#actioncontroller-parameters-no-longer-inherits-from-hashwithindifferentaccess)
This uses !empty? instead of any?
It also casts to a hash before calling `#first` on params
Fixes #121

### CODE REVIEW

**Comment by beneggett** [comment]
This fixes for us on 5.1; would love to see this merged + gem version update

**Comment by jherdman** [comment]
Apologies for piling onto this ticket, but this would be really great to see merged in.

**Comment by phoffer** [comment]
@ljachymczyk is there anything else that may be needed for Rails 5.1 compatibility?

**Comment by wynksaiddestroy** [comment]
Any chance on getting this pull request merged quickly?

**Comment by business-phil** [comment]
+1 on including a version bump with this PR.  I'm currently pointing directly to the most recent SHA since the version wasn't updated with the last group of PRs.

**Comment by beneggett** [comment]
@ljachymczyk anything we can do to help this go through? Thanks

**Comment by ljachymczyk** [comment]
Merged and bumped version to 1.2.1. 
Thanks!

**Comment by beneggett** [comment]
Thanks!
